[ED27] [ED63] [ED53] - Import Partners/Products/Chart of Accounts + Accounting configuration of all of them + Banking Information
Xevlabs/axelor-open-suite pull request #12
Opened 2022-06-21 18:52 UTC by nassym-xevlabs

- Added all the files needed to import partners, products and chart of accounts (as well as their accounting configuration)
- Implemented the Banking Info configuration (attached to corrected companies and Partners)

Warning: on my local setup, the Axelor demo data import for accounting and base modules took approx. 2hours+ and more than 100Gb in temp files (I don't know it the fact that I have the TRACE config for logs plays a role but I prefer to let you all know). So be sure to have an appropriate setup before testing it (server, database instance, etc.) to avoid any issue.

2022-06-21 19:00 UTC, nassym-xevlabs commented
Don't know why 2 Menu.xml are changed as they were not edited and pulled from main branch to create that one.

2022-06-24 15:41 UTC, AntoineXev commented
@nassym-xevlabs could you fix the issue related to the lang folders on this one ?

2022-06-24 22:21 UTC, nassym-xevlabs commented
Everything has been updated and all the fixes implemented, including the deletion of the EN folders in base and accounting modules.

All the changes have been pushed to the branch.

2022-06-26 17:08 UTC, AntoineXevlabs requested changes
Needs Formating and comments, but rest looks good !

2022-06-26 17:08 UTC, AntoineXevlabs commented on axelor-account/src/main/resources/demo/account-config.xml
> +    to="bankDetails" update="true" if="bankDetails_importId"/> </input> -->
Code could be removed (do not let comment that are not real ones in the code)

2022-06-26 17:08 UTC, AntoineXevlabs commented on axelor-account/src/main/resources/demo/account-config.xml
> +    search="self.importId = :partner_importId"/> </input> -->
Same here

2022-06-26 17:08 UTC, AntoineXevlabs commented on axelor-base/src/main/resources/demo/base-config.xml
> +
Same

2022-06-26 17:08 UTC, AntoineXevlabs commented on axelor-base/src/main/resources/demo/base-config.xml
> +
Too many spaces

2022-06-26 17:08 UTC, AntoineXevlabs commented on axelor-base/src/main/resources/demo/base-config.xml
> +    to="bankDetails" update="true" if="bankDetails_importId"/> </input> -->
same

2022-06-27 14:36 UTC, AntoineXevlabs approved these changes

2022-06-27 15:19 UTC, merged